### ISSUE TITLE
[Client] 상세페이지 구현

### ISSUE THREAD

**Issue by doehyunbaek** [codestates/momojito_Client#2]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 상세 페이지 구현

### TODO
1. [ ] 공통 레이아웃 구현
2. [ ] 일반 상세페이지 구현
3. [ ] 이색 칵테일 상세페이지 구현

### Estimated time
> Pick one
### `3h`
